version: '3.7'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always

  cast-and-crew:
    build:
      context: .
    image: castandcrew:latest
    container_name: castandcrew
    ports:
    - "3000:3000"